Enh 434 no refresh pantry
TylerMetz/Saucier720 pull request #481
Opened 2023-08-08 01:33 UTC by samforstot

## Describe your changes
Now the page no longer refreshes when adding items to pantry, list, or scrolling through recipes
## Issue ticket number and link
#434

2023-08-09 05:23 UTC, rileycleavenger requested changes
Ok this change is BIG TIME, it makes the app run so much more seamlessly, its mad hype. However, here are some things I thought of that you should add before we merge this:

- [x] Change the "Add Cookbook" button to also not require a refresh (similar to save filters button)
- [x] When selecting "Add Cookbook" or "Save Filters" hide their respective menus so that users know their selection worked
- [ ] Verify that when adding an item to your pantry it will update the recommended recipes accordingly without the need for a refresh. Based on backend it should, but you should confirm this.

2023-08-09 05:23 UTC, rileycleavenger commented on src/Scrapers/KrogerScraper.py
idk how this made it in there, it isn't even the finished version, can you remove it from this PR?

2023-08-09 19:06 UTC, samforstot commented on src/Scrapers/KrogerScraper.py
Yeah I gotchu, couldve been a git add . from before

2023-08-10 00:56 UTC, samforstot commented
@rileycleavenger All of these things are now solved, found a new bug where when the pantry is empty it requires a refresh

2023-08-10 01:55 UTC, samforstot commented
Solved previous bug, will add no refresh on deals page soon.

2023-08-10 01:58 UTC, rileycleavenger commented
Fire, will review after you change the deals page

2023-08-10 02:01 UTC, rileycleavenger requested changes
I know this is nit picky, but can you remove the commented out refreshes? Also will approve after making deals page static

2023-08-10 02:01 UTC, rileycleavenger commented on Saucier720-app/src/app/recipes/FEC/filter-menu/filter-menu.component.ts
> +      //window.location.reload(); // refresh page to show updated data
can you remove all of the commented out refreshes?

2023-08-10 02:01 UTC, rileycleavenger commented on Saucier720-app/src/app/recipes/FEC/new-recipe/new-recipe.component.ts
> +        //window.location.reload(); // refresh page to show updated data
here

2023-08-10 02:01 UTC, rileycleavenger commented on Saucier720-app/src/app/recipes/FEC/recipe-nav-bar/recipe-nav-bar.component.ts
> +      //window.location.reload();
here

2023-08-10 02:01 UTC, rileycleavenger commented on Saucier720-app/src/app/recipes/FEC/recipe-nav-bar/recipe-nav-bar.component.ts
> +      //window.location.reload();
here

2023-08-11 03:45 UTC, rileycleavenger approved these changes
LGTM! These changes are game changer for running the app as an SPA, it makes it so much more fluid. I love.

2023-08-11 23:43 UTC, merged